<meta charset="UTF-8"/>
<?php
/*VARIAVEIS NÃO FUNCIONAM QUANDO COLOCADAS ENTRE ASPAS SIMPLES*/
/*VARIAVEIS FUNCIONAM QUANDO COLOCADAS ENTRE ASPAS DUPLAS*/
/*USAMOS O (.) PARA CONCATENAR(JUNTAR) DOIS VALORES*/

$nome = 'Erandir';
echo "Meu nome é \"$nome\"";